### ISSUE TITLE
【MathJax】 Display Problem

### ISSUE THREAD

**Issue by TangLongbin** [zhonger/jekyll-theme-H2O-ac#14]
# Two Problems

## Problem-1

![image](https://github.com/zhonger/jekyll-theme-H2O-ac/assets/73875400/98f9b321-4c3a-4fd2-a3a0-00629dc47ea6)

As shown above, inline LATEX failed to **be processed**.

## Problem-2

![image](https://github.com/zhonger/jekyll-theme-H2O-ac/assets/73875400/41ecbff2-02e0-471c-b570-d408be1d8ff3)

Formulations are **not centred**.

## Display in VSCode by **Markdown Preview Enhanced**

I set the extension to use **MathJax**, it works well locally.  
I check the `_include`, the `mathjax.html` file looks like out of date.  

![image](https://github.com/zhonger/jekyll-theme-H2O-ac/assets/73875400/ebf9da56-79ce-480e-9d22-b9add49021ae)

![image](https://github.com/zhonger/jekyll-theme-H2O-ac/assets/73875400/521cda86-0729-417b-900f-76ac00294da8)

## Possible Solution

Update the `mathjax.html` file.  
If you're too busy nowadays, you can give me an instruction. Then I'll try to solve it!

**Comment by zhonger** [comment]
Thank you for your kindness and contribution. 
Sorry for the late reply.
I will review your pull and merge it soon.

**Comment by zhonger** [comment]
I think it's very good, so I have merged it.
Thank you for your contribution again.
