### ISSUE TITLE
tags页面的footer有两行

### ISSUE THREAD

**Issue by alphandbelt1** [zhonger/jekyll-theme-H2O-ac#30]

**Comment by zhonger** [comment]
![image](https://github.com/user-attachments/assets/9bec27c9-7866-4533-a1b3-9d85907b7108)

哈哈哈，还的确是。平时不访问 tags 页面都没发现。

感谢反馈，计划修复。

**Comment by alphandbelt1** [comment]
非常喜欢您的这个主题，期待您的修复。。。

**Comment by zhonger** [comment]
该 Bug 已经在 v1.3.5 版本修复 682e2a97c065a6290ddafdfbabfed48d35c4630c ，使用 `bundle upgrade` 即可升级使用最新版本。

欢迎继续关注、使用本主题。
